### ISSUE TITLE
Tests required?

### ISSUE THREAD

**Issue by gareth-ib** [RonasIT/laravel-swagger#2]
Does this require tests in order to run? I've set it up according to your instructions but calling the doc display page is still not generating anything.

All I get is `Failed to load spec.` error on the swagger page.

Is there supposed to be a console command to generate the doc file? Or is that supposed to happen on call of the `'route'` url from the config?

thanks

**Comment by Asxer** [comment]
@gareth-ib Yes, main goal of plugin is collect documentation while tests runs as it mentioned in documentation:

`This plugin is designed to gather information and generate documentation about your Rest-Api while passing the tests.`

**Comment by gareth-ib** [comment]
ok so it needs controller tests to even start making the swagger config file? I have tests but not on the controllers.
Is there a way to see what is running? I'm having trouble following the execution path in your package. How does the test let your system know what route the controller action belongs to?
Does the controller test need certain tags in order to work? Could you put sample code in an example folder? For a route with the matching controller and test unit?

thanks!

**Comment by gareth-ib** [comment]
Ok so I had to change the `env` to `testing` in order for it to try and run.. that requirement should probably be in the docs.

going to the `/auto-doc/documentation` url, throws an error with no message from
`ronasit\local-data-collector\src\DataCollectors\LocalDataCollector.php`

from these lines

```php
    public function getDocumentation() {
        if (!file_exists($this->prodFilePath)) {
            throw new FileNotFoundException();
        }
         $fileContent = file_get_contents($this->prodFilePath);
         return json_decode($fileContent);
    }
```

like is it trying to check if the file exists before generating it?

Is this meant to be used by going to a normal URL then the swagger doc takes over? Sorry, I'm really not sure what is going on as far as making the process actually run

**Comment by pursehouse** [comment]
ah ok thanks.

Since you know the code, can you picture an easy way to separate the phpunit aspect from the swagger doc aspect? So the testing part isn't a limiting factor, instead it could run off the routes system

**Comment by Asxer** [comment]
@pursehouse Sorry but i'm not sure that I realized what are you want to reach. Could you please clarify that?

**Comment by gareth-ib** [comment]
Basically just able to run without the test controllers. Have it loop
through the routes instead of the tests

**Comment by gareth-ib** [comment]
You've written so many fine working pieces to convert laravel structured code into swagger, so it'd be nice to be able to use those without it being the exact test process you've wrapped those functionalities inside of

**Comment by Asxer** [comment]
@gareth-ib I do not understand what are you mean under test controllers. 
Do you want to collect documentation through AutoDocMiddleware declaration in project and running some script which will call all your routes? Actually you can do that if you will write your own DataCollector which will store temporary documentation in some file. 

A written LocalDataCollector store incomplete documentation in static variable(because it is not clearing between tests) and save collected documentation after all tests successfully passed. So it doesn't satisfy your needs and you must reimplement it.

What must you do for that:
1. Implement your own DataCollector
2. Set it in confg `auto-doc.data_collector`
3. Set env variable `APP_ENV` to testing while you are going to collect documentation.

**Comment by Asxer** [comment]
@gareth-ib Actually this plugin dedicated for collecting permanent documentation which are generated on deployment because deployment process must contains tests running. 
Main idea of testing process in our development workflow is "Do not test your code. Test your use cases". Tests run in separated environments with clear DB and middleware separate test process from dev/production process by `APP_ENV` variable. You can check it in AutoDocMiddleware. 
Running your code from console is not a testing of REST-API, so this plugin is not what you need. 

You can check some plugins in swagger ecosystem and I belive you can find something usefull. I think you can check [Dredd](https://dredd.readthedocs.io/en/latest/) for example

**Comment by gareth-ib** [comment]
yeah I've looked at Dredd, I'm not trying to do anything with testing in this aspect. Testing is good but I'd like to be able to generate the swagger doc outside of testing. Because that swagger doc is used by other systems and can itself be a map for external testing systems instead of internal written testers. Like right now I have to add swagger doc to a large set of existing projects that don't have testing ( and there is no time to add testing to them ), but do have proper structure otherwise. So requiring internal testing is sort of a limiting factor, as opposed to being a nice extra feature. Know what I mean?

**Comment by Asxer** [comment]
Close because of inactivity
